//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourBacon.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string NotificationFrom { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
    
        public virtual User User { get; set; }
        public virtual NotificationStatu NotificationStatu { get; set; }
        public virtual NotificationStatu NotificationStatu1 { get; set; }
    }
}
