//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveYourBacon.API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int TransactionTypeId { get; set; }
        public decimal DefaultAmount { get; set; }
        public Nullable<decimal> CustomAmount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> TransactionSourceId { get; set; }
        public Nullable<int> TransactionPeriodId { get; set; }
        public Nullable<decimal> AmountContributed { get; set; }
        public Nullable<decimal> SurplusDeficit { get; set; }
        public System.DateTime WhenCreated { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TransactionPeriod TransactionPeriod { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
